<Project>

  <PropertyGroup>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>Recommended</AnalysisMode>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <Company>apptade</Company>
    <Authors>apptade</Authors>

    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RepositoryType>git</RepositoryType>

    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>

    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageReadmeFile Condition="Exists('README.md')">README.md</PackageReadmeFile>

    <NuGetPackagePrefix>CrCore</NuGetPackagePrefix>
  </PropertyGroup>

  <ItemGroup Condition="Exists('README.md')">
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>