name: NuGet Packages Publisher

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - run: dotnet restore

      - run: dotnet build -c Release --no-restore

      - name: Pack
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          dotnet pack \
            -c Release \
            --no-build \
            -o ./artifacts \
            -p:PackageVersion=${VERSION#v}

      - name: NuGet Login
        id: login
        uses: NuGet/login@v1
        with:
          user: ${{ github.repository_owner }}

      - name: Publish
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --source https://api.nuget.org/v3/index.json \
            --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" \
            --skip-duplicate
